version: '3.9'
name: project-name
services:
    app:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        volumes:
            - ./:/app
            - ./docker/php/php.ini:/usr/etc/php/conf.d/dev.ini
        working_dir: /app
        depends_on:
            - database
            - cache
        networks:
            - app-custom-bridge
    web:
        image: nginx:1.25
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./public/:/app/public
        networks:
            - app-custom-bridge
        depends_on:
            - app
    database:
        image: postgres:15.2
        restart: unless-stopped
        ports:
            - "5432:5432"
        networks:
            - app-custom-bridge
        environment:
            POSTGRES_PASSWORD: root
    cache:
        image: redis:7
        restart: unless-stopped
        networks:
            - app-custom-bridge
        ports:
            - "6379:6379"

networks:
    app-custom-bridge:
        driver: bridge
